version: '3.9'

services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./.var/mysql:/var/lib/mysql/
        restart: always
        ports:
            - 3307:3306
        environment:
            MYSQL_DATABASE: wp_test
            MYSQL_ROOT_PASSWORD: 123
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - wp-network

    php:
        image: php:7.4.15-fpm-alpine3.13
        volumes:
            - ./dist:/var/www/html
        ports:
            - 9001:9000
        links:
            - mysql
        restart: always
        networks:
            - wp-network

    nginx:
        image: nginx:1.19.6-alpine
        container_name: nginx
        volumes:
            - ./.var/nginx:/etc/nginx/conf.d
            - ./dist:/var/www/html
        ports:
            - 8000:80
        links:
            - mysql
        networks:
            - wp-network

networks:
    wp-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
