const purgecss = require("@fullhuman/postcss-purgecss");
const purgecssWordpress = require("purgecss-with-wordpress");

module.exports = {
    plugins: [
        require("autoprefixer"),
        require("cssnano")({
            preset: "default",
        }),
        purgecss({
            content: ["./src/**/*.php"],
            keyframes: true,
            safelist: {
                standard: [
                    ...purgecssWordpress.safelist,
                    "fp-nav",
                    'relative',
                    'search-inclusions',
                    'header-mobile-show',
                    'header__search-item',
                    "iframe",
                    "fp-left",
                    "fp-tooltip",
                    "procedure__form-item",
                    "show-first-form",
                    "#tns2-iw",
                    "show-second-form",
                    "fp-sr-only",
                    "disabled",
                    "current-menu-item",
                    "is-open",
                    "micromodal-slide",
                    "active",
                    "accord-open",
                    "tiny-slider",
                    "terms-footer",
                    "popup-input",
                    "btn-send-me",
                    "lang-item",
                    "region__item",
                    "lang-item-first",
                    "body-overlay",
                    "current-lang",
                    "menu-item",
                    "with-arrow",
                    "diam",
                    "subnav-show",
                    "footer-hide",
                    "showBtn",
                    "random",
                    "hide-mobile",
                    "social__link",
                    "body-overlay",
                    "subnav__list--show",
                    "col-lg-2",
                    "footer-menu",
                    "showItem",
                    "danger",
                    "menu-item-51",
                    "yep",
                    "button",
                    "hideItem",
                    "admin-bar",
                    "tns-nav",
                    /^nav-/,
                    /^owl/,
                    /^tns/,
                    /^wpcf7/,
                    /^screen/,
                    /^col/,
                    /^tns/,
                ],
                deep: [/social__link$/],
                greedy: [],
                keyframes: [],
                variables: [],
            },
        }),
    ],
};
